# This is a basic workflow to help you get started with Actions
 
name: E2E Testing (Self-Hosted) with Flyway and Playwright Integration Testing
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "release" branch
   push:
    branches:
      - master

env:
  # Enable this for additional debug logging
  ACTIONS_RUNNER_DEBUG: true 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flyway-initalise-db:
    name: flyway initialise db
    runs-on: self-hosted
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2
      # Runs the Flyway Clean command against the Build database
      - name: initialise db
        run: |
          cd 'C:\flyway-commandline-9.11.0-windows-x64\flyway-9.11.0\'
          flyway info
          flyway clean
          flyway migrate


  integration-test:
    name: playwright e2e test
    runs-on: self-hosted
    needs: flyway-initalise-db
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Tests
        working-directory: ./client/src
        run: |
          npx playwright test E2E.spec.js

