# Example of Unit Test with types of TDD: Return Value & Check state changes

name: Unit Tests

on:
  push:
    branches: [feature, master]
      
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Tests
        working-directory: ./client
        run: |
          npm test App_Unit.test.js -- --coverage --coverageDirectory=client/coverage/ 

      - name: fix code coverage paths
        working-directory: ./client
        run: |
          sed -i 's/github/workspace/client/client/coverage/g' /github/workspace/client/client/coverage/lcov.info

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
         fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
