# Example of Unit Test with types of TDD: Return Value & Check state changes

name: Unit Tests

on:
  push:
    branches: [feature, master]
      
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Tests
        working-directory: ./client
        run: |
          npm test App_Unit.test.js -- --coverage --coverageDirectory=client/coverage/ 

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        #with:
        #  fetch-depth: 0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
