# Example of Unit Test with types of TDD: Return Value & Check state changes

name: Unit Tests

on:
  push:
    branches: [feature, master]
      
jobs:
  Jest:
    #runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Tests
        working-directory: ./client
        run: |
          npm test App_Unit.test.js -- --coverage --coverageDirectory=client/coverage/ 

      - name: SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          fetch-depth: 0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_LOCAL }}
          #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: http://localhost:9000/dashboard?id=UEM-JS-DEMO 
