name: Unit Tests

on:
  push:
    branches:
      - feature
      
jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: npm install

      - name: Run Tests
        working-directory: ./client
        run: |
          npm test -- App_Unit.test.js